application:
    build: docker/code
    volumes:
        - .:/var/www/symfony
        - ./docker/logs/symfony:/var/www/symfony/app/logs
    tty: true
db:
    image: mariadb:latest
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: mysql
        MYSQL_DATABASE: symfony_dev
clamav:
    image: dinkel/clamavd
    expose:
        - 3310:3310
    volumes_from:
        - application
php:
    build: docker/php-fpm
    expose:
        - 9000:9000
    volumes_from:
        - application
        - clamav
    links:
        - db
        - clamav
    environment:
      - SYMFONY__DATABASE__USER=root
      - SYMFONY__DATABASE__PASSWORD=mysql
      - SYMFONY__DATABASE__NAME=symfony
      - SYMFONY__DATABASE__HOST=db
      - SYMFONY_ENV=dev
nginx:
    build: docker/nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./docker/logs/nginx/:/var/log/nginx
elk:
    image: willdurand/elk
    ports:
        - 81:80
    volumes:
        - ./docker/elk/logstash:/etc/logstash
        - ./docker/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - application
        - php
        - nginx
