uco_user:
    resource: '@UcoUserBundle/Resources/config/routing.xml'
    prefix:   '/'

ssp_bundle:
    resource: '@SSPGuardBundle/Resources/config/routing/connect.xml'

# app/config/routing.yml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# liip image
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# uploader
oneup_uploader:
    resource: .
    type: uploader

app:
    resource: "@AppBundle/Controller/Frontend/"
    type:     annotation
    prefix:     /{_locale}/
    defaults:
        _locale: en
    requirements:
        _locale: |en|es
