#FosUserBundle Routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

sir_login:
    pattern: /login/check-sir

# EasyAdmin
easy_admin_bundle:
    resource: "@AppBundle/Controller/Backend/AdminController.php"
    type:     annotation
    prefix:   /admin

oneup_uploader:
    resource: .
    type: uploader

app:
    resource: "@AppBundle/Controller/Frontend/"
    type:     annotation
    prefix:     /{_locale}/
    defaults:
        _locale: en
    requirements:
        _locale: |en|es
