security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        AppBundle\Model\FileInterface: sha512

 
    role_hierarchy:
        ROLE_ADMIN:             ['ROLE_USER', 'ROLE_SONATA_ADMIN']
        ROLE_SUPER_ADMIN:       ['ROLE_ADMIN', 'ROLE_ALLOWED_TO_SWITCH']
 
    providers:
        uco_user_provider:
            id: 'uco.user.provider'


    firewalls:
        dev:
            pattern:  '^/(_(profiler|wdt)|css|images|js)/'
            security: false

        main:
            pattern: '^/'
            guard:
                provider: 'uco_user_provider'
                authenticators:
                    - 'uco.admin.authenticator'
            form_login:
                always_use_default_target_path: false
                target_path_parameter:          '_target_path'
            logout:
                path: '/logout'
                target: '/'
            anonymous:   true
            switch_user: true
 
    access_control:
        - { path: '^/login$', role: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/connect', role: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/check', role: 'ROLE_USER' }
        - { path: '^/_uploader', role: 'ROLE_USER' }
        - { path: '^/admin/', role: 'ROLE_ADMIN' }
