# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    my_user_provider:
        class: AppBundle\Security\Core\User\FOSUBUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager, { sir: sir_id }, @doctrine.orm.entity_manager]

# EVENT LISTENERS

    consigna.security.listener:
        class: AppBundle\EventListener\SecurityConsignaListener
        arguments: [ @security.encoder_factory ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    consigna.virus.listener:
        class: AppBundle\EventListener\VirusConsignaListener
        arguments: [@logger,@doctrine.orm.entity_manager,%antivirus_path%,@mailer]
        tags:
            - { name: kernel.event_subscriber }

    consigna.log.listener:
        class: AppBundle\EventListener\LogListener
        arguments: [@logger,@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_subscriber }

    consigna.user_login.listener:
        class: AppBundle\EventListener\UserLoginListener
        arguments: [@session, @security.authorization_checker]
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    consigna.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: [%supported_languages%]
        tags:
            - { name: kernel.event_subscriber }

    consigna.event_listener.upload_listener:
        class: AppBundle\EventListener\UploadListener
        arguments: [ @service_container ]
        tags:
            - { name: 'kernel.event_listener', event: 'oneup_uploader.pre_upload', method: 'onPreUpload' }
            - { name: 'kernel.event_listener', event: 'oneup_uploader.post_upload', method: 'onUpload' }
    appbundle.type.tags_text:
        class: AppBundle\Form\Type\TagsTextType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: tags_text }

# UPLOADER NAMER

    consigna.namer.real:
        class: AppBundle\Uploader\Namer\RealNamer

# VOTERS

    consigna.file_voter:
        class:      AppBundle\Security\Voter\FileVoter
        arguments: [@session]
        public:     false
        tags:
           - { name: security.voter }

    consigna.folder_voter:
        class:      AppBundle\Security\Voter\FolderVoter
        arguments: [@session]
        public:     false
        tags:
           - { name: security.voter }

    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }